CC = clang++

NAME = sfml.so

CFLAGS = -Wall -Werror -Wextra -std=c++11

SFML_FLAGS = -lsfml-graphics -lsfml-window -lsfml-system
SFML_LIBS = -L /usr/lib/x86_64-linux-gnu/

INC = sfml.hpp

SRC = sfml.cpp

OBJ = $(SRC:.cpp=.o)

