#On Mac OS X, compile with:
#all:
#	g++ -dynamiclib -flat_namespace myclass.cpp -o myclass.so
#	g++ class_user.cpp -o class_user

#On Linux, compile with:

#g++ -fPIC -shared myclass.cc -o myclass.so
#g++ class_user.cc -ldl -o class_user